### ISSUE TITLE
events.js:141       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by CyberSardinha** [sushilks/alexaHarmonyApp#23]
HI,

I don't know if anyone can help me but I'm trying to setup this on my raspberry pi and I'm getting this error:

```
pi@raspberrypi:~/alexaHarmonyApp $ node server.js
Listening on port 443
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1225:19)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at Object.<anonymous> (/home/pi/alexaHarmonyApp/server.js:50:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

```

Can someone help me?

**Comment by sushilks** [comment]
Not sure but 'EACCES' seems to be permission type issue. 
may be you need root access.

**Comment by CyberSardinha** [comment]
That solved it
Thank you
