### ISSUE TITLE
problem with identity - login to harmony

### ISSUE THREAD

**Issue by sawdustdood** [sushilks/alexaHarmonyApp#6]
I have configured the skill, setup the hub, made small modifications to the scripts, etc..  However, when testing an utterance, it appears the JS is having some sort of issue related to the Logitech site or something.  Any thoughts or suggestions?  I have also tried to change the 'guest' login to my harmony account/password with no success.

I am running nodejs 5.6.0 on OS/X Yosemite with a very recent clone of this code.  What gets returned is the following in response to a 'Ask remote watch TV' test from Amazon dev site for the skill.  

Thanks!
# T

mini:alexaHarmonyApp myuser$ node server.js
Listening on port 8443
Turning on TV Mode!
/Users/myuser/nodejs/alexaHarmonyApp/node_modules/harmonyhubjs-client/lib/login/hub.js:63
                        if(response.identity && response.identity !== undefined) {
                                   ^

TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/harmonyhubjs-client/lib/login/hub.js:63:15)
    at emitOne (events.js:90:13)
    at Client.emit (events.js:182:7)
    at Client.onStanza (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/node-xmpp-client/index.js:224:14)
    at emitOne (events.js:90:13)
    at Connection.emit (events.js:182:7)
    at Connection.onStanza (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:370:14)
    at StreamParser.<anonymous> (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:226:14)
    at emitOne (events.js:90:13)
    at StreamParser.emit (events.js:182:7)
    at SaxLtx.<anonymous> (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:59:22)
    at emitOne (events.js:90:13)
    at SaxLtx.emit (events.js:182:7)
    at SaxLtx._handleTagOpening (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/ltx/lib/parsers/ltx.js:35:12)
    at SaxLtx.write (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/ltx/lib/parsers/ltx.js:95:18)
    at StreamParser.write (/Users/myuser/nodejs/alexaHarmonyApp/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:128:21)

**Comment by sushilks** [comment]
This is same as https://github.com/sushilks/harmonyHubCLI/issues/1
It's been fixed recently, need to checkout the project fresh and reinstall "npm install".

**Comment by sushilks** [comment]
I will close the issue as it's been fixed, let me know if you see any more problems.

**Comment by sawdustdood** [comment]
Sorry, I got sidetracked. Can confirm its working

**Comment by lanzer** [comment]
Just installed the service today and I'm getting the same error.  Did Harmony changed something on their end? 

I'm seeing no response from the harmony server:

received XMPP stanza: <iq xmlns:stream="http://etherx.jabber.org/streams"/>
received XMPP stanza: <iq id="788701" to="guest" type="get" xmlns:stream="http://etherx.jabber.org/streams"><oa xmlns="connect.logitech.com" mime="vnd.logitech.connect/vnd.logitech.pair" errorcode="200" errorstring="OK"/></iq>
received response: ""
